CREATE DATABASE THUCANNHANH
USE THUCANNHANH

CREATE TABLE NHANVIEN(
	MANV VARCHAR(10) PRIMARY KEY,
	TENNV NVARCHAR(50) NOT NULL,
	GIOITINH NVARCHAR(3) CHECK (GIOITINH = N'nam' OR GIOITINH = N'nữ'),
	NGAYSINH DATE,
	DIACHI NVARCHAR(50),
	SDT VARCHAR(10),
	TRANGTHAI BIT DEFAULT 1,
)

CREATE TABLE KHACHHANG(
	MAKH VARCHAR(10) PRIMARY KEY,
	TENKH NVARCHAR(50) NOT NULL,
	SDT VARCHAR(10),
	DIACHI NVARCHAR(50),
	TRANGTHAI BIT DEFAULT 1,
)

CREATE TABLE NHACUNGCAP(
	MANCC VARCHAR(10) PRIMARY KEY,
	TENNCC NVARCHAR(50) NOT NULL,
	SDT VARCHAR(10),
	DIACHI NVARCHAR(50),
	TRANGTHAI BIT DEFAULT 1,
)

CREATE TABLE NGUYENLIEU(
	MANL VARCHAR(10) PRIMARY KEY,
	TENNL NVARCHAR(50) NOT NULL,
	SL INT NOT NULL,
	DONVITINH NVARCHAR(30) NOT NULL,
	DONGIA MONEY NOT NULL,
	HINHANH VARCHAR(100) NOT NULL,
	LOAI NVARCHAR(30) NOT NULL,
	TRANGTHAI BIT DEFAULT 1,
)

CREATE TABLE MONAN(
	MAMA VARCHAR(10) PRIMARY KEY,
	TENMA NVARCHAR(50) NOT NULL,
	SL INT NOT NULL,
	DONVITINH NVARCHAR(30) NOT NULL,
	DONGIA MONEY NOT NULL,
	HINHANH VARCHAR(100) NOT NULL,
	LOAI NVARCHAR(30) NOT NULL,
	TRANGTHAI BIT DEFAULT 1,
)

CREATE TABLE CHITIETMONAN(
	MAMA VARCHAR(10),
	MANL VARCHAR(10),
	SLNL INT NOT NULL,
	PRIMARY KEY (MAMA, MANL),
)

CREATE TABLE KHUYENMAI(
	MAKM VARCHAR(10) PRIMARY KEY,
	TENKM NVARCHAR(100) NOT NULL,
	DIEUKIEN NVARCHAR(100) NOT NULL,
	GIAMGIA FLOAT NOT NULL,
	NGAY_BD DATE NOT NULL,
	NGAY_KT DATE NOT NULL,
	TRANGTHAI BIT DEFAULT 1,
)

CREATE TABLE HOADON(
	MAHD VARCHAR(10) PRIMARY KEY,
	NGAYLAPHD DATE NOT NULL,
	TONGTIEN MONEY NOT NULL,
	TRANGTHAI BIT DEFAULT 1,
	MANV VARCHAR(10),
	MAKH VARCHAR(10),
	MAKM VARCHAR(10),
)

CREATE TABLE CHITIETHOADON(
	MAHD VARCHAR(10),
	MAMA VARCHAR(10),
	SL INT NOT NULL,
	GHICHU NVARCHAR(100),
	PRIMARY KEY (MAHD, MAMA),
)

CREATE TABLE PHIEUNHAP(
	MAPN VARCHAR(10) PRIMARY KEY,
	NGAYNHAP DATE NOT NULL,
	TONGTIEN MONEY NOT NULL,
	MANV VARCHAR(10),
	MANCC VARCHAR(10),
)

CREATE TABLE CHITIETPHIEUNHAP(
	MAPN VARCHAR(10),
	MANL VARCHAR(10),
	SL INT NOT NULL,
	PRIMARY KEY (MAPN, MANL),
)

CREATE TABLE QUYEN(
	MAQUYEN VARCHAR(10) PRIMARY KEY,
	TENQUYEN NVARCHAR(50) NOT NULL,
	MOTA NVARCHAR(200),
	TRANGTHAI BIT DEFAULT 1,
)

CREATE TABLE CHUCNANG(
	MACN VARCHAR(10) PRIMARY KEY,
	TENCN NVARCHAR(50) NOT NULL,
	MOTA NVARCHAR(200),
)
 
CREATE TABLE CHITIETPHANQUYEN(
	MAQUYEN VARCHAR(10),
	MACN VARCHAR(10),
	PRIMARY KEY (MAQUYEN, MACN),
)

CREATE TABLE TAIKHOAN(
	USERNAME VARCHAR(10) PRIMARY KEY,
	MATKHAU VARCHAR(20) NOT NULL,
	TRANGTHAI BIT DEFAULT 1,
	MAQUYEN VARCHAR(10),
)

ALTER TABLE HOADON ADD CONSTRAINT HD_MANV_FK FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV)

ALTER TABLE HOADON ADD CONSTRAINT HD_MAKH_FK FOREIGN KEY (MAKH) REFERENCES KHACHHANG (MAKH)

ALTER TABLE HOADON ADD CONSTRAINT HD_MAKM_FK FOREIGN KEY (MAKM) REFERENCES KHUYENMAI (MAKM)

ALTER TABLE CHITIETHOADON ADD CONSTRAINT CTHD_MAHD_FK FOREIGN KEY (MAHD) REFERENCES HOADON (MAHD)

ALTER TABLE CHITIETHOADON ADD CONSTRAINT CTHD_MAMA_FK FOREIGN KEY (MAMA) REFERENCES MONAN (MAMA)

ALTER TABLE PHIEUNHAP ADD CONSTRAINT PN_MANCC_FK FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP (MANCC)

ALTER TABLE PHIEUNHAP ADD CONSTRAINT PN_MANV_FK FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV)

ALTER TABLE CHITIETPHIEUNHAP ADD CONSTRAINT CTPN_MAPN_FK FOREIGN KEY (MAPN) REFERENCES PHIEUNHAP (MAPN)

ALTER TABLE CHITIETPHIEUNHAP ADD CONSTRAINT CTPN_MANL_FK FOREIGN KEY (MANL) REFERENCES NGUYENLIEU (MANL)

ALTER TABLE CHITIETPHANQUYEN ADD CONSTRAINT CTPQ_MAQUYEN_FK FOREIGN KEY (MAQUYEN) REFERENCES QUYEN (MAQUYEN)

ALTER TABLE CHITIETPHANQUYEN ADD CONSTRAINT CTPQ_MACN_FK FOREIGN KEY (MACN) REFERENCES CHUCNANG (MACN)

ALTER TABLE TAIKHOAN ADD CONSTRAINT TK_MAQUYEN_FK FOREIGN KEY (MAQUYEN) REFERENCES QUYEN (MAQUYEN)

ALTER TABLE TAIKHOAN ADD CONSTRAINT USERNAME_FK FOREIGN KEY (USERNAME) REFERENCES NHANVIEN (MANV)

ALTER TABLE CHITIETMONAN ADD CONSTRAINT CTMA_MAMA_FK FOREIGN KEY (MAMA) REFERENCES MONAN (MAMA)

ALTER TABLE CHITIETMONAN ADD CONSTRAINT CTMA_MANL_FK FOREIGN KEY (MANL) REFERENCES NGUYENLIEU (MANL)

INSERT INTO NHANVIEN(MANV, TENNV, GIOITINH, NGAYSINH, DIACHI, SDT)
VALUES
('admin', N'Nguyễn Văn A', N'nam', '2003-08-17', N'Quận 1, Thành phố Hồ Chí Minh', '0123456789'),
('NV001', N'Trần Thị B', N'nữ', '2001-09-18', N'Quận 2, Thành phố Hồ Chí Minh', '0987654321'),
('NV002', N'Lê Văn C', N'nam', '2004-10-19', N'Quận 3, Thành phố Hồ Chí Minh', '0123123123'),
('NV003', N'Nguyễn Thị D', N'nữ', '1999-11-20', N'Quận 4, Thành phố Hồ Chí Minh', '0456456456'),
('NV004', N'Phan Văn E', N'nam', '2000-12-21', N'Quận 5, Thành phố Hồ Chí Minh', '0789789789')

INSERT INTO TAIKHOAN(USERNAME, MATKHAU)
VALUES
('admin', 'admin'),
('NV001', 'nv001'),
('NV002', 'nv002'),
('NV003', 'nv003'),
('NV004', 'nv004')